Feature/den component
teamo2dev/todo-frontend pull request #1
Opened 2021-04-06 10:11 UTC by shinYeongHyeon

2021-04-06 16:07 UTC, stevejkang requested changes
리뷰 남겨두었습니다 !

2021-04-06 16:07 UTC, stevejkang commented on src/component/tag/todoParagraph.stories.tsx
> +export const DefaultKorean = () => <TodoParagraph string='기본 TodoParagraph 문구' />
여기만 마지막 엔터 추가부탁드려요!

2021-04-13 10:22 UTC, shinYeongHyeon commented on src/component/tag/todoParagraph.stories.tsx
> +export const DefaultKorean = () => <TodoParagraph string='기본 TodoParagraph 문구' />
완뇨

2021-04-13 10:23 UTC, stevejkang approved these changes

2021-04-13 10:23 UTC, merged